### ISSUE TITLE
UX audit report (2nd December)

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-2#222]
## UX notes
These checkboxes will be converted into issues after discussion

- [x] How to write update? Probably comes up because of old campaign hogging address
- [x] How to manage campaigns that were created with different address? (Permissions to edit and write updates over account?)
- [x] We should show project address (projectview & donate, default hidden?)
- [x] "Similar projects" missing type styling (projectview)
- [x] I would love to see more metadata for the project surfaced (creation, update date from updates tab and owner linked to profile)
- [x] User might expect to "go back" (createproject)
- [ ] AFTER MVP Description needs support for "rich text" (createproject)
- [x] KAY GETS NEW KEY Choose location needs to be more intuitive (createproject) and has errors
- [ ] If fiat gets to be properly integrated we might need to separate certain values into fiat and crypto - i.e. value of assets in wallet, vs value of assets in project
- [x] #255 Project cards on homepage still feel strange - very small click target (learn more), donate CTA seems to prominent given that I would like info BEFORE I donate to some project (feels clickbatey)
- [x] We should optimize for performance, loading projects from the server takes way too long
- [ ] google font seems to load only after first draw happened already

### Testlog:
✅ - Sign In 
✅ - Donate with Metamask
✅ - Load more projects

### Create Project (local):
✅ - Sign In
✅ - Fill out all fields
✅ - Fill out location
✅ - High Five
✅ - Project can be visited (worked on staging)
✅ - Project is shown on frontend (worked on staging)
 ✅ - At one point the project called "da" took over the route /projects and 'show more projects button' was routing there as well

### Missing links, content and functionality:

`homepage`

- [ ] Project filtering by tags
- [ ] Project filtering by location
- [ ] Project filtering by likes(?)
- [ ] Project filtering by amount (why?)
- [ ] Do something with wallet address (i.e. copy to clipboard, direct to etherscan)
- [x] My Projects
- [ ] Settings
- [x] Support

`projects-card`

- [ ] description blurb
- [ ] givers are hardcoded
- [ ] donations are hardcoded
- [ ] donated funds amount is hardcoded
- [x] tags
- [x] likes

`projects view`

- [ ] Project creator is still placeholder (Project Organization)
- [x] Donate container is *sticky*
- [ ] *Other* button not working (purpose unclear)

`my account`
- [ ] change wallet address (is this even possible?)
- [x] my donations still hardcoded?
- [x] my projets still hardcoded?
- [x] assets value is hardcoded
- [x] my projets still hardcoded?
- [x] wallet settings should link to tor.us wallet application
- [x] support should link to chat with a fallback for email

**Comment by mateodaza** [comment]
Yes, I will upload all my changes before the meeting and let's try all of this over this version

**Comment by markoprljic** [comment]
Anything here missing from design @geleeroyale ?

**Comment by geleeroyale** [comment]
@markoprljic Yes for sure - there are some that could use design. Mind that these are my suggestions and impressions and not hard requests:

- [ ] We should show project address (projectview & donate, default hidden?)
- [ ] I would love to see more metadata for the project surfaced (funds collected, creation, update date from updates tab and owner linked to profile)
- [ ] Choose location needs to be more intuitive (createproject) and has errors
- [ ] If fiat gets to be properly integrated we might need to separate certain values into fiat and crypto - i.e. value of assets in wallet, vs value of assets in project

**Comment by markoprljic** [comment]
> Description needs support for "rich text" (createproject)

@geleeroyale We want to avoid this because we don't want users to go crazy with styling. We want all our project pages to get the same formatting and look consistent across the site.

**Comment by markoprljic** [comment]
> User might expect to "go back" (createproject)

@mateodaza I added the Back button on project creation flow. When user goes back, the previous sections remained saved. Leave green checkmarks for sections that are already filled in. 

<img width="487" alt="Image 2020-12-08 at 12 48 00 pm" src="https://user-images.githubusercontent.com/5704285/101480188-9fbd8a80-3953-11eb-9b75-214264dfcb4a.png">

**Comment by markoprljic** [comment]
> We should show project address (projectview & donate, default hidden?)

@geleeroyale I added the wallet address under the Donations tab (I don't think it is relevant on any other section on the Project details page).

@mateodaza Wallet address is (can be) a link. On hover color pink, external link opens explorer (?)

<img width="821" alt="Image 2020-12-08 at 10 47 30 am" src="https://user-images.githubusercontent.com/5704285/101480367-e14e3580-3953-11eb-8c8d-d1bcbddb970c.png">

**Comment by markoprljic** [comment]
> If fiat gets to be properly integrated we might need to separate certain values into fiat and crypto - i.e. value of assets in wallet, vs value of assets in project

@geleeroyale Is this what you refer to? 

![Uploading Image 2020-12-08 at 12.51.08 pm.png…]()

**Comment by geleeroyale** [comment]
> > Description needs support for "rich text" (createproject)
> 
> @geleeroyale We want to avoid this because we don't want users to go crazy with styling. We want all our project pages to get the same formatting and look consistent across the site. 
> 

Ok. I have just a different opinion. Basic things like inserting a link, picture, headline, quote are standard these days.

At this point no one testing it worked with a lot of text. Without some visual hierarchy I fear it's just not possible to make a professional project description.

I would not call it "going crazy" 😊

**Comment by markoprljic** [comment]
> Project cards on homepage still feel strange - very small click target (learn more), donate CTA seems to prominent given that I would like info BEFORE I donate to some project (feels clickbatey)

@geleeroyale Indeed it does feel clickbatey :) The original card styling has not been fully applied like the example below. The whole card should be link to project details, including the link Learn more, leaving the Donate button prominent for more accessible donations directly from the homepage. 
Down the road, I'd love to see the "Add to cart" feature implemented.

<img width="486" alt="Image 2020-12-08 at 12 53 07 pm" src="https://user-images.githubusercontent.com/5704285/101480852-8832d180-3954-11eb-829e-03e45781062c.png">

**Comment by markoprljic** [comment]
> I would love to see more metadata for the project surfaced (funds collected, creation, update date from updates tab and owner linked to profile)

Can you please clarify this a bit more? 

>  Choose location needs to be more intuitive (createproject) and has errors

Cannot test this due to errorrs, it was working fine before.

**Comment by markoprljic** [comment]
> > > Description needs support for "rich text" (createproject)
> > 
> > 
> > @geleeroyale We want to avoid this because we don't want users to go crazy with styling. We want all our project pages to get the same formatting and look consistent across the site.
> 
> Ok. I have just a different opinion. Basic things like inserting a link, picture, headline, quote are standard these days.
> 
> At this point no one testing it worked with a lot of text. Without some visual hierarchy I fear it's just not possible to make a professional project description.
> 
> I would not call it "going crazy" 😊

I was questioning this earlier when doing the design. Since we were going fast and cutting scope I didn't want to implement a rich text editor because I wanted to force a visual hierarchy and that had more implications on the dev side. 

This is a good topic to discuss on our next call.

**Comment by markoprljic** [comment]
> > I would love to see more metadata for the project surfaced (funds collected, creation, update date from updates tab and owner linked to profile)
> 
> Can you please clarify this a bit more?
> 
> > Choose location needs to be more intuitive (createproject) and has errors
> 
> Cannot test this due to errorrs, it was working fine before.

@geleeroyale When you get a chance to answer above, please. Thanks!

**Comment by geleeroyale** [comment]
Hey @markoprljic - currently it's less a design issue but rather an implementation issue.

Once it works again let's see if additional design is needed!

**Comment by willyogo** [comment]
> > Project cards on homepage still feel strange - very small click target (learn more), donate CTA seems to prominent given that I would like info BEFORE I donate to some project (feels clickbatey)
> 
> @geleeroyale Indeed it does feel clickbatey :) The original card styling has not been fully applied like the example below. The whole card should be link to project details, including the link Learn more, leaving the Donate button prominent for more accessible donations directly from the homepage.
> Down the road, I'd love to see the "Add to cart" feature implemented.
> 
> <img alt="Image 2020-12-08 at 12 53 07 pm" width="486" src="https://user-images.githubusercontent.com/5704285/101480852-8832d180-3954-11eb-829e-03e45781062c.png">

Created a ticket for this: https://github.com/Giveth/giveth-2/issues/256

**Comment by mateodaza** [comment]
@markoprljic I noticed that nowhere on the project view we are displaying its location. Please help me choose the perfect spot for it! 

![image](https://user-images.githubusercontent.com/18689480/102517467-11858a80-405e-11eb-91bb-03acf2473655.png)

**Comment by markoprljic** [comment]
Right aligned from the project owener name. What say you? 

<img width="796" alt="Image 2020-12-17 at 5 55 10 pm" src="https://user-images.githubusercontent.com/5704285/102518059-1a438400-4091-11eb-93f5-6e4242b6b52c.png">

**Comment by geleeroyale** [comment]
@mateodaza Please review line items from initial description

**Comment by mateodaza** [comment]
Gave a check to this audit and these are the main issues we should discuss and solve

- [ ] Project filtering
- [ ] What we do we with organization placeholder on project view
- [ ] Rich text support
- [ ] Google font load time
- [ ] Settings link on homepage menu, also  do something with wallet address
- [ ] I would love to see more metadata for the project surfaced (funds collected, creation, update date from updates tab and owner linked to profile)
- [ ] If fiat gets to be properly integrated we might need to separate certain values into fiat and crypto - i.e. value of assets in wallet, vs value of assets in project

**Comment by geleeroyale** [comment]
@geleeroyale reminder to put this into issues and sort it by mvp and fast-follow

**Comment by jamespfarrell** [comment]
Mateo to create separate issues for the above.

**Comment by mateodaza** [comment]
> Gave a check to this audit and these are the main issues we should discuss and solve
> 
> * [ ]  Project filtering
> * [x]  What we do we with organization placeholder on project view
> * [ ]  Rich text support
> * [ ]  Google font load time
> * [ ]  Settings link on homepage menu, also  do something with wallet address
> * [ ]  I would love to see more metadata for the project surfaced (funds collected, creation, update date from updates tab and owner linked to profile)
> * [ ]  If fiat gets to be properly integrated we might need to separate certain values into fiat and crypto - i.e. value of assets in wallet, vs value of assets in project

Closing having created related issues: 
#390, #391, #392, #393
