### ISSUE TITLE
MVP launch

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-2#291]
## 📋 Anything to add?
Collects all issues that are needed for "proper" MVP release. Once cleared, MVP can be deployed and announced and we enter the new phase of `maintenance and support` for the running deployment, as well as working on `post MVP features`

## ⏰ Urgency/Deadline/Blockers?
We are way past our target and should look to finishing this asap.

## ❓ Why is it important?
Development for MVP is blocking advanced feature requests, potential recode and whitelabeling

## 🎉 Subtasks

- [ ] Need to set a deadline for this to align deliverables
- [ ] Include all needed issues and organize last sprints
- [ ] Prepare communication materials

## 🤼‍ Reviewer

@willyogo

**Comment by markoprljic** [comment]
Can we review this Epic and potentially close it, move issues that are Fast follow into Backlog or something?
