### ISSUE TITLE
Automate database backups - backend maintenance and QOL

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-2#386]
We identified a few essential workflows that we need to setup in order for soft launch to be satisfying for campaign owners.

Following needs to be possible on the backend:

- [ ] Backup full database automatically and regularly
- [x] Backup full system regularly
- [x] Make backup script
- [ ] Setup CI
- [x] Have a way to import a backup
- [x] Be able to edit database entries to correct issues
- [x] Have a way to invalidate user session after App update (@jamespfarrell)

**Comment by jamespfarrell** [comment]
@geleeroyale Database entries can be edited directly. If you need help setting up a GUI for the db, I can help with DBeaver

**Comment by geleeroyale** [comment]
Hey that sounds great!

**Comment by geleeroyale** [comment]
- Set appointment after soft launch to run DBeaver
- automated backup service

**Comment by jamespfarrell** [comment]
@geleeroyale 
For backups I'm thinking, we can easily create cron jobs with [node cron](https://github.com/kelektiv/node-cron)

Did a quick search [someone thinking the same](https://soshace.com/automated-postgresql-backups-with-nodejs-and-bash/)

I would say this is a dev ops task if you're interested?

**Comment by jamespfarrell** [comment]
[JS code to dump the database](https://stackoverflow.com/questions/30921435/nodejs-backup-mysql-database)

**Comment by geleeroyale** [comment]
Yes - totally taking that under the devops umbrella. I will mess around a bit with the suggestions you sent!

**Comment by geleeroyale** [comment]
Step 1 complete - I have DBeaver running and connected to the database (staging for now)

**Comment by geleeroyale** [comment]
Will start with backup only for Post-valentines sprint

**Comment by jamespfarrell** [comment]
Cron tab reference - https://crontab.guru/every-2-hours

**Comment by geleeroyale** [comment]
Full system backups are now scheduled via digitalocean
