### ISSUE TITLE
Giveth 2 - Create a Project (front end)

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#54]
As a user, I want to be able to create a project for raising and allocating funds. 
[mockups](https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=976%3A158&scaling=scale-down-width)

**Comment by willyogo** [comment]
Here are the designs from Marko 🎉 https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=976%3A158&viewport=479%2C379%2C0.03263114020228386&scaling=scale-down-width

These have been approved and are ready to be brought to life on top of the simple, but elegant backend that @jamespfarrell has developed.

The UI/UX for the project creation flow was inspired by TypeForm. If you're not already familiar with TypeForm's awesome UX, please check it out to get an understanding of the desired look and feel.

User Story: As a user, I want to create a project on Giveth 2 so I can share my project with the world and begin accepting donations.

Steps in project creation flow:

When a user clicks 'Create a Project' on v2.giveth.io, they enter the first step of the project creation flow
Step 1: Project Name (Mockup)
Details: Limit length of name to 55 characters. Display character count. When a user clicks 'Next', the project name is added to the object and the user continues to Step 2.
Step 2: Project Description (Mockup)
Details: Limit length of description to 2000 characters. Display character count. If a user clicks 'How to write a good project description' they see the Project Description Instruction Modal. If a user clicks 'Next', the project description is added to the object and the user continues to Step 3.
Step 2.5: Project Description Instruction Modal (Mockup)
Details: Use placeholder links for now (v2.giveth.io/projects). All links open in a new tab. If a user clicks 'Close', the modal closes.
Step 3: Project Category (Mockup)
Details: Project Categories from the DB are displayed in a list with checkboxes. Users must select one, and can also select multiple. When a user clicks 'Next', all selected categories are added to the object and user continues to Step 4.
Step 4: Location (mockup)
Details: This one probably warrants its own issue, so feel free to skip or to put a placeholder in for this now. Ideally users can type any location (ie. address, zip code, city, province, country, continent) as a tool such as google maps autocompletes. Then, when a user has selected a location from autocomplete, data gets saved as a point on the map or as an area. Users can also check a box if the project has a 'Global' impact.
Step 5: Project Image (Mockup)
Details: Users can click 'Upload from Computer' to select a file to upload. They can also select an image from the gallery. (use placeholder images for now). When a user clicks 'Next' the image is added to the object and the user proceeds to the final confirmation step.
Step 6: Confirm and Publish (Mockup)
Details: Users can see their previous inputs (Description is truncated to first 200 characters). When a user clicks 'START RAISING FUNDS', their project details object is sent to the addProject endpoint on the GraphQL server. If an error occurs, display the error message below the CTA. If successful, user continues to the success screen. Stretch: add a loading state to the 'Start Raising Funds' button if it's taking a bit to load.
Step 7: High Five! (Mockup)
Details: User sees their Project Card, which links to their project page. Users see a link to 'View my project' or 'Go to Homepage' ; User also sees links to share on Twitter, Facebook, or LinkedIn. Draft copy for sharing: "Interested in supporting the [Project Category] cause? Check out the project we just launched on @Givethio. 100% of each donation goes directly to [Project Name]. [Project URL]"

AC:

Until a user has input a valid response, the 'Next' button is disabled and the user cannot continue (a response is required for each step)
At each step of the flow, users see a link to edit previous inputs. If a user clicks 'Edit' they are returned to that step and can see their input.
UI matches mockups as closely as reasonable
UX matches TypeForm as closely as reasonable

BTW, there is a step in the current flow that we're removing "Is your project part of an organization?" Please do not include this step in the flow.

Thank you!! Please let me or Marko know if you have any questions about UI/UX! 🚀

**Comment by willyogo** [comment]
If you're here from Gitcoin and interested in picking up this grant, let us know in the giveth discord channel, #giveth-2-dev 

We can help you get your environment up and running and answer any questions.

**Join Giveth Discord**

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 266 years, 3 months from now.
Please review their action plans below:


**1) [brymut](https://gitcoin.co/brymut) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/Giveth/giveth-2/54/100023498?mutate_worker_action=approve&worker=brymut) | [reject worker](https://gitcoin.co/issue/Giveth/giveth-2/54/100023498?mutate_worker_action=reject&worker=brymut))_.**

Currently, I've got a working understanding of giveth and the donation Dapp and the current WIP state of the giveth-2 application and introduced myself on the Discord chat ( BryanMutai#6546 ). 

I've got an understanding of the Typeform-ish inspired flow required for this epic, and familiarised myself with the Figma desktop design that have been shared. Still yet to see the design for the mobile flow however I can still workout some responsive layout solutions based on the current designs.

The action plan would be to work through the issues that have been created for this epic on Github from the initial Project name input to the high-five. With a pull request through each related GitHub issue, I would set up the layout as per the designs and capture user input into local browser storage, along with testing and accessibility and internalisation and any related user & developer documentation that maybe later useful for the project. As well as adding new Github issues as per new needs arising.

Regular communication aside from the Github issue comments and pull request reviews would go on in Discord.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/Giveth/giveth-2/54/100023498).

**Comment by gitcoinbot** [comment]
@brymut Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-2/54/100023498?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-2/54/100023498?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-2/54/100023498?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-2/54/100023498?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-2/54/100023498?snooze=100)

**Comment by brymut** [comment]
@gitcoinbot still working on this.

**Comment by zoek1** [comment]
Hi! I'm pretty interested on implement the fronted for Giveth v2. I'm a fullstack developer, I have experience working with React and delivering sites. I frequently built features for Gitcoin that requires good communication with the design and engineering team,  also i worked with Raid Guild to build a great feature for Gitcoin and the communication was by discord, so I'll update my status frequently. Also, I'm a solidity developer in the case that such skill will be required. I love the design and i really like deliver this :D This is my discord user zoek#0055. i'm open co tollaborate on this or any other issue to speed up the things

@willyogo

**Comment by brymut** [comment]
@gitcoinbot Still working on this.

**Comment by geleeroyale** [comment]
> Hi! I'm pretty interested on implement the fronted for Giveth v2. I'm a fullstack developer, I have experience working with React and delivering sites. I frequently built features for Gitcoin that requires good communication with the design and engineering team, also i worked with Raid Guild to build a great feature for Gitcoin and the communication was by discord, so I'll update my status frequently. Also, I'm a solidity developer in the case that such skill will be required. I love the design and i really like deliver this :D This is my discord user zoek#0055. i'm open co collaborate on this or any other issue to speed up the things
> 
> https://gitcoin.co/zoek1
> 
> @willyogo

Hey @zoek1 

For this issue we found @brymut to work on it and he is on a good way already to finish it.

You can join our dev call on Sunday 17:30 CEST (watch gitveth2-dev channel on discord) and say hello. I am sure there will be more tasks for contributors down the line and it is always nice to being in more developers.

**Comment by gitcoinbot** [comment]
@brymut Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-2/54/100023498?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-2/54/100023498?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-2/54/100023498?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-2/54/100023498?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-2/54/100023498?snooze=100)

**Comment by aminlatifi** [comment]
@brymut if you need to upload file somewhere can use pinata so far. See this as a prototype https://github.com/Giveth/giveth-2/issues/51#issuecomment-675022770

**Comment by gitcoinbot** [comment]
@brymut Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-2/54/100023498?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-2/54/100023498?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-2/54/100023498?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-2/54/100023498?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-2/54/100023498?snooze=100)
