### ISSUE TITLE
As a Giver, I want to know which projects are eligible for GIVBacks

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-2#632]
## 📋 Anything to add?

- A **GIVBack Badge** is displayed on Verified project's cards and profiles
- If a user hovers over a GIVBack Badge, they see a tooltip, "Givers to this project are eligible to receive up to 75% of their donation back in GIV tokens. _Learn more about GIVBacks_."
- It would be really nice to make sure people know that there is a % of the GIV that they get is claimable and a % that is Locked... we don't want to have them feel like we are tricking them...

## 🎉 Subtasks

- [ ] Design GIVBack badge or similar label to be displayed on each project
- [ ] Add Tooltip on hover
- [ ] Create a new page for GIVBack and GIV tokens that explains everything in detail
- [ ] Create a medium blog post explaining how GIVBacks work

**Comment by markoprljic** [comment]
![Image 2021-03-31 at 4 33 19 pm](https://user-images.githubusercontent.com/5704285/113161598-d428bf80-923e-11eb-8642-912f386ca234.jpg)
