### ISSUE TITLE
Add Prometheus Monitoring and Alerts on backend servers

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-2#662]
## 📋 Anything to add?
We have Prometheus running on the Giveth1 infrastructure

## ⏰ Urgency/Deadline/Blockers?
not totally urgent but considered due diligence

## ❓ Why is it important?
Almost as important as backups and downtime should be avoided at all cost (especially on live deployment). Also - if something goes offline it is usually hard to find the cause - monitoring and alerts help by alarming what happened when and usually indicate a problem before the server goes down

## 🎉 Subtasks

- [x] install node-exporter on `dev`, `staging`, `live`impact-graph deployments
- [x] configure node sources in prometheus instance
- [x] set up dashboards in grafana
