### ISSUE TITLE
Remove the ability to use a contract address as a project if it is only on 1 chain and not the other

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#722]
## 📋 Anything to add?

Sadly, we live in a multichain world and smart contracts (DAOs, Multisigs) only exist on 1 chain :-(

Their are a lot of gnosis safes that are actually on multiple chains... so that is ok (Yay handshake!) but the Giveth multisig for instance is not!

## ⏰ Urgency/Deadline/Blockers?

Very Urgent!

## ❓ Why is it important?

Money is being lost!!!

## 🎉 Subtasks

- [ ] Check to see if any projects on Giveth.io are already contract addresses
- [ ] If ^^^ then reach out to the projects and ask them to change their address to an EOA 
- [ ] Implement and isContract check on Ethereum at project creation
- [ ] Implement and isContract check on xDai at project creation
- [ ] Implement a check that if the address is a contract on both chains or not a contract on either chaing, its ok! If it is on one chain but not the other, do not let them go forward with that address.
- [ ] Create an option to request this feature to validate the use case

## 🤼‍ Reviewer

@markoprljic @Danibelle @GriffGreen

**Comment by jamespfarrell** [comment]
Please test

**Comment by divine-comedian** [comment]
I took a contract address from Balancer  - this one precisely - https://etherscan.io/token/0x59a19d8c652fa0284f44113d0ff9aba70bd46fb4?a=0x59a19d8c652fa0284f44113d0ff9aba70bd46fb4
and it allowed me to make a project no problem, the address itself exists on xDAI it is however empty. 

![image](https://user-images.githubusercontent.com/67759413/113921735-5facce00-97b4-11eb-9892-36eb259dd9aa.png)

![image](https://user-images.githubusercontent.com/67759413/113921785-7521f800-97b4-11eb-89fc-56da6d8f5c8e.png)

## Also
I took the PIEDAO contract and made a giveth project with it - 
![image](https://user-images.githubusercontent.com/67759413/113925058-8f5dd500-97b8-11eb-841b-b31acead7b7e.png)
 again no problem in successfully creating a project. 
 
![image](https://user-images.githubusercontent.com/67759413/113925197-bc11ec80-97b8-11eb-9a4e-fdb6d9753e9c.png)


Is there another way I should be testing this? Is there a different sort of address we should be using to test? @jamespfarrell

**Comment by laurenluz** [comment]
assigning you @jamespfarrell to check this out re: the testing discussion here and in #722, and all my million messages in discord :)

Main points/questions:

1. Are we disallowing the user to put contract address entirely (as it says #722) or are we allowing contracts that accept donations on both chains (as it says in this issue)?

2. How do we determine if an address is on one chain or both? I tried checking on blockscout and found that the giveth multisig comes up on there on xdai. So confusing because this issue was raised because we lost a HNY donation into the void because that address *doesn't* receive on xdai.

3. Did we scan through all the projects already to determine if there are any contracts on there that could cause money to go into the void? Did we send notifications to ask projects to change the address? Or did we remove them entirely?

4. Did we do that scan as well on staging?

**Comment by jamespfarrell** [comment]
Ok, I got to the bottom of this, and it's a little problematic.

Our method of detection is to call getCode on the contract:
![image.png](https://images.zenhubusercontent.com/5807a7a095e42b6c5baabbd3/4882d429-c699-4da0-8c09-57adf06e9a25)

if it's not a smart contract, but an externally owned account it returns '0x'

so I think it's a good solution (the only one I could find)

the problem is that we are multichain on the dapp

so the user could be on xdai, ropsten or main net

and it will only check if the contract exists on the network metamask is connected to, so if the contract doesn't exist there it will think there's no contract and that there's no problem.

This is most important on live. Where we have 2 networks. 

So we could have the issue that the user is connected to mainnet and puts in an xDai smart contract address.

We could also do it on the donation side... check if it exists before allowing donations to it, that's not really possible as I believe a wallet like Torus can generate an address and private key before it exists on the blockchain.

So yeah I believe the only thing we can do is check xDai and Mainnet to know if there is a smart contract wallet on either chain, and disallow it, unless it exists on both chains.

**Comment by laurenluz** [comment]
It's possible to check on both chains though, right? So as to avoid the issue you mentioned...

> it will only check if the contract exists on the network metamask is connected to, so if the contract doesn't exist there it will think there's no contract and that there's no problem

let me know if/when it's ready to test - also if you have an easy way for me to double check that if the smart contract address I'm using is on one chain or both, would be good to know (and much appreciated).

You rock, James!

**Comment by divine-comedian** [comment]
as per https://github.com/Giveth/giveth-2/issues/727

looks like we are not allowing smart contract addresses to be used as recipients. This particular issue is no longer relevant since we've made smart contracts entirely non-compatible.
