### ISSUE TITLE
Dashboard for Giveth.io Statistics

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-2#816]
## 📋 Anything to add?
Do we have an easy way to see/monitor product activity stats?
Number of projects, donations, updates, total value donated etc.

How hard/easy is it to pull all this from db? Pulling the data out is easy.... Most of the work would be in creating the visual appearance.

It would be great to have a dashboard for both io and trace, let's focus on Giveth.io for now.

Would it be easier to use a dashboard UI template for the front end and reskin it?

Some interesting data from the database:
- 236 donations
- $4,996 raised
- average donation = 21.16$
- 190 donations in xDAI - 639$ (average 3.36$)

## ❓ Why is it important?
Track user activity, use to make informed decisions when engaging in marketing activities, user acquisition, and retention. 
This and other ideas may be useful for our communications updates.

## 🎉 Subtasks

- [ ] Discuss and make a list of data / metrics
- [ ] Explore available open-source bootstrap front-end that are easy to re-skin
- [ ] Mockup UI
- [ ] Create subdomain dashboard.giveth.io or stats.giveth.io
- [ ] Code FE and Deploy to subdomain

## 🤼‍ Reviewer

@markoprljic 

## 🔗 Work doc - inspirational links

Open source Dashboard Templates https://www.creative-tim.com/blog/web-design/free-dashboard-templates/
More free templates https://365webresources.com/latest-free-dashboard-admin-frameworks-for-front-end-developers/

**Comment by WhyldWanderer** [comment]
related issue https://github.com/Giveth/giveth-planning/issues/167

**Comment by WhyldWanderer** [comment]
Link to the current dashboard...
https://giveth-dashboard.herokuapp.com/public/dashboard/5218ea60-42ef-416b-80f0-4b58fc78ef49
